api:
  quranapi:
    host: http://localhost:9021
    connection:
      connectTimeoutSeconds: 10
      readTimeoutSeconds: 50
      writeTimeoutSeconds: 50
      keep-alive: true
      tcp-no-delay: true

